# Generated by Django 4.1.4 on 2023-07-06 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='simulado',
        ),
        migrations.AddField(
            model_name='simulado',
            name='questao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulado.questao'),
        ),
    ]
