# Generated by Django 4.1.4 on 2023-07-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0002_remove_questao_simulado_simulado_questao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulado',
            name='questao',
        ),
        migrations.AddField(
            model_name='simulado',
            name='questao',
            field=models.ManyToManyField(to='simulado.questao'),
        ),
    ]
