# Generated by Django 4.1.4 on 2023-07-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0003_remove_simulado_questao_simulado_questao'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativa',
            name='alternativa_correta',
            field=models.BooleanField(default=False),
        ),
    ]
