# Generated by Django 4.1.4 on 2023-07-06 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0004_alternativa_alternativa_correta'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='tema',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='simulado.tema'),
        ),
    ]
